#!/bin/bash

set -e

SCRIPT=$(realpath -s "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

. /script/install_source.sh

mkdir -p /build_log

declare -a recipes=()
recipes+=(basic/Man-pages)
recipes+=(basic/Iana-Etc)
recipes+=(basic/Glibc)
recipes+=(basic/Zlib)
recipes+=(basic/Bzip2)
recipes+=(basic/Xz)
recipes+=(basic/Zstd)
recipes+=(basic/File)
recipes+=(basic/Readline)
recipes+=(basic/M4)
recipes+=(basic/Bc)
recipes+=(basic/Flex)
recipes+=(basic/Tcl)
recipes+=(basic/Expect)
recipes+=(basic/DejaGNU)
recipes+=(basic/Pkgconf)
recipes+=(basic/Binutils)
recipes+=(basic/GMP)
recipes+=(basic/MPFR)
recipes+=(basic/MPC)
recipes+=(basic/Attr)
recipes+=(basic/Acl)
recipes+=(basic/Libcap)
recipes+=(basic/Libxcrypt)
recipes+=(basic/Shadow)
recipes+=(basic/GCC)
recipes+=(basic/Ncurses)
recipes+=(basic/Sed)
recipes+=(basic/Psmisc)
recipes+=(basic/Gettext)
recipes+=(basic/Bison)
recipes+=(basic/Grep)
recipes+=(basic/Bash)
recipes+=(basic/Libtool)
recipes+=(basic/GDBM)
recipes+=(basic/Gperf)
recipes+=(basic/Expat)
recipes+=(basic/Inetutils)
recipes+=(basic/Less)
recipes+=(basic/Perl)
recipes+=(basic/XML::Parser)
recipes+=(basic/Intltool)
recipes+=(basic/Autoconf)
recipes+=(basic/Automake)
recipes+=(basic/OpenSSL)
recipes+=(basic/Kmod)
recipes+=(basic/Elfutils)
recipes+=(basic/Libffi)
recipes+=(basic/Python)
recipes+=(basic/Flit-Core)
recipes+=(basic/Wheel)
recipes+=(basic/Setuptools)
recipes+=(basic/Ninja)
recipes+=(basic/Meson)
recipes+=(basic/Coreutils)
recipes+=(basic/Check)
recipes+=(basic/Diffutils)
recipes+=(basic/Gawk)
recipes+=(basic/Findutils)
recipes+=(basic/Groff)
if test $USE_UEFI -eq 1; then
    recipes+=(basic/mandoc)
    recipes+=(basic/efivar)
    recipes+=(basic/popt)
    recipes+=(basic/efibootmgr)
    recipes+=(basic/freetype)
    recipes+=(basic/grub-efi)
else
recipes+=(GRUB)
fi
recipes+=(basic/Gzip)
recipes+=(basic/IPRoute2)
recipes+=(basic/Kbd)
recipes+=(basic/Libpipeline)
recipes+=(basic/Make)
recipes+=(basic/Patch)
recipes+=(basic/Tar)
recipes+=(basic/Texinfo)
recipes+=(basic/Vim)
recipes+=(basic/MarkupSafe)
recipes+=(basic/Jinja2)
recipes+=(basic/Systemd)
recipes+=(basic/D-Bus)
recipes+=(basic/Man-DB)
recipes+=(basic/Procps-ng)
recipes+=(basic/Util-linux)
recipes+=(basic/E2fsprogs)

install_package_list

rm -rf /tmp/*
find /usr/lib /usr/libexec -name \*.la -delete
find /usr -depth -name $(uname -m)-lfs-linux-gnu\* | xargs rm -rf
userdel -r tester
