#!/bin/bash

set -e

SCRIPT=$(realpath -s "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

RECIPES_DIR=$SCRIPT_PATH/recipes/$FERNINUX_TARGET_ARCH
SOURCES_ROOT_DIR=/sources

echo "Creating Xorg build env"
export XORG_PREFIX=/usr
export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

#if sudo installed
#cat > /etc/sudoers.d/xorg << EOF
#Defaults env_keep += XORG_PREFIX
#Defaults env_keep += XORG_CONFIG
#EOF

cat > /etc/profile.d/xorg.sh << EOF
XORG_PREFIX="$XORG_PREFIX"
XORG_CONFIG="--prefix=\$XORG_PREFIX --sysconfdir=/etc --localstatedir=/var --disable-static"
export XORG_PREFIX XORG_CONFIG
EOF
chmod 644 /etc/profile.d/xorg.sh

declare -a recipes=()
recipes+=(xorg/util-macros)
recipes+=(xorg/xorgproto)
recipes+=(xorg/libXau)
recipes+=(xorg/libXdmcp)
recipes+=(xorg/xcb-proto)
recipes+=(xorg/libxcb)
recipes+=(graphical_libraries/fontconfig)
#auto generated by Xorg_Libraries.sh
recipes+=(xorg/xtrans)
recipes+=(xorg/libX11)
recipes+=(xorg/libXext)
recipes+=(xorg/libFS)
recipes+=(xorg/libICE)
recipes+=(xorg/libSM)
recipes+=(xorg/libXScrnSaver)
recipes+=(xorg/libXt)
recipes+=(xorg/libXmu)
recipes+=(xorg/libXpm)
recipes+=(xorg/libXaw)
recipes+=(xorg/libXfixes)
recipes+=(xorg/libXcomposite)
recipes+=(xorg/libXrender)
recipes+=(xorg/libXcursor)
recipes+=(xorg/libXdamage)
recipes+=(xorg/libfontenc)
recipes+=(xorg/libXfont2)
recipes+=(xorg/libXft)
recipes+=(xorg/libXi)
recipes+=(xorg/libXinerama)
recipes+=(xorg/libXrandr)
recipes+=(xorg/libXres)
recipes+=(xorg/libXtst)
recipes+=(xorg/libXv)
recipes+=(xorg/libXvMC)
recipes+=(xorg/libXxf86dga)
recipes+=(xorg/libXxf86vm)
recipes+=(xorg/libpciaccess)
recipes+=(xorg/libxkbfile)
recipes+=(xorg/libxshmfence)
# end Xorg Libraries
recipes+=(xorg/libxcvt)
recipes+=(xorg/xcb-util)
recipes+=(xorg/xcb-util-image)
recipes+=(xorg/xcb-util-keysyms)
recipes+=(xorg/xcb-util-renderutil)
recipes+=(xorg/xcb-util-wm)
recipes+=(xorg/xcb-util-cursor)
recipes+=(libraries/libarchive)
recipes+=(libraries/libuv)
recipes+=(libraries/nghttp2)
recipes+=(libraries/libunwind)
recipes+=(libraries/libxml2)
recipes+=(libraries/wayland)
recipes+=(libraries/wayland-protocols)
recipes+=(network/curl)
recipes+=(programming/cmake)
recipes+=(programming/llvm)
recipes+=(programming/mako)
recipes+=(graphical_libraries/libdrm)
recipes+=(xorg/Mesa)
recipes+=(xorg/xbitmaps)
recipes+=(graphical_libraries/libpng)
#auto generated by Xorg_Applications.sh
recipes+=(xorg/iceauth)
recipes+=(xorg/luit)
recipes+=(xorg/mkfontscale)
recipes+=(xorg/sessreg)
recipes+=(xorg/setxkbmap)
recipes+=(xorg/smproxy)
recipes+=(xorg/x11perf)
recipes+=(xorg/xauth)
recipes+=(xorg/xbacklight)
recipes+=(xorg/xcmsdb)
recipes+=(xorg/xcursorgen)
recipes+=(xorg/xdpyinfo)
recipes+=(xorg/xdriinfo)
recipes+=(xorg/xev)
recipes+=(xorg/xgamma)
recipes+=(xorg/xhost)
recipes+=(xorg/xinput)
recipes+=(xorg/xkbcomp)
recipes+=(xorg/xkbevd)
recipes+=(xorg/xkbutils)
recipes+=(xorg/xkill)
recipes+=(xorg/xlsatoms)
recipes+=(xorg/xlsclients)
recipes+=(xorg/xmessage)
recipes+=(xorg/xmodmap)
recipes+=(xorg/xpr)
recipes+=(xorg/xprop)
recipes+=(xorg/xrandr)
recipes+=(xorg/xrdb)
recipes+=(xorg/xrefresh)
recipes+=(xorg/xset)
recipes+=(xorg/xsetroot)
recipes+=(xorg/xvinfo)
recipes+=(xorg/xwd)
recipes+=(xorg/xwininfo)
recipes+=(xorg/xwud)
# end Xorg_Applications
recipes+=(xorg/xcursor-themes)
# auto generated by Xorg_Fonts.sh
recipes+=(xorg/font-util)
recipes+=(xorg/encodings)
recipes+=(xorg/font-alias)
recipes+=(xorg/font-adobe-utopia-type1)
recipes+=(xorg/font-bh-ttf)
recipes+=(xorg/font-bh-type1)
recipes+=(xorg/font-ibm-type1)
recipes+=(xorg/font-misc-ethiopic)
recipes+=(xorg/font-xfree86-type1)
# end Xorg_fonts
recipes+=(xorg/XKeyboardConfig)
recipes+=(graphical_libraries/pixman)
recipes+=(graphical_libraries/libepoxy)
recipes+=(network_libraries/libtirpc)
recipes+=(xorg/Xwayland)
recipes+=(xorg/Xorg-Server)
recipes+=(xorg/libevdev)
recipes+=(libraries/mtdev)
recipes+=(xorg/xf86-input-evdev)
recipes+=(xorg/libinput)
recipes+=(xorg/xf86-input-libinput)
recipes+=(xorg/xf86-input-synaptics)
recipes+=(xorg/xf86-input-wacom)
recipes+=(xorg/twm)
recipes+=(xorg/xterm)
recipes+=(xorg/xclock)
recipes+=(xorg/xinit)

cd $RECIPES_DIR

for file in "${recipes[@]}"
do
    if [ -x "$file.sh" ]; then
        . ./"$file.sh"
	echo "extracting files from $SRC_COMPRESSED_FILE"
	rm -rf $SOURCES_ROOT_DIR/$SRC_FOLDER
	tar xvf $SOURCES_ROOT_DIR/$SRC_COMPRESSED_FILE -C $SOURCES_ROOT_DIR
	cd $SOURCES_ROOT_DIR/$SRC_FOLDER
	build_source_package
	rm -rf $SOURCES_ROOT_DIR/$SRC_FOLDER
	cd $RECIPES_DIR
    else
        echo "File $file is not executable."
    fi
done

install -v -d -m755 /usr/share/fonts                               &&
ln -svfn $XORG_PREFIX/share/fonts/X11/OTF /usr/share/fonts/X11-OTF &&
ln -svfn $XORG_PREFIX/share/fonts/X11/TTF /usr/share/fonts/X11-TTF
